(function(a){function h(c){this.target=c}var e=function(c){return new h(c)},f=document.getElementsByTagName("script"),f=f[f.length-1],d={avatarCore:h.prototype,base:b,baseURL:f.src.replace(/\/[^\/]+$/,"/")||window.Web.Config.Environment.Url.HttpCache + window.Web.Config.Environment.Path.Scripts+'NEG/',CDNTimestamp:f.getAttribute("data-CDNTimestamp")||"",isDebug:"",init:function(){a.NEG=e.base.merge(e,b);d.isDebug||delete a.NEG.base}},b={base:d};e.base=d;e.toString=function(){return"baishuiz@gmail.com"};a.NEG=b})(this);
(function(a){base=a.base||{};var h={merge:function(e){for(var a=1;a<arguments.length;a++){var d=arguments[a],b;for(b in d)e[b]=d[b]}return e},NS:function(e,a){for(var d=e.split("."),b=a||window||{},c=0,j=d.length;c<j;c++)b[d[c]]=b[d[c]]||{},b=b[d[c]];return b},ArrayIndexOf:Array.prototype.indexOf?function(e,a){e=[].slice.call(e,0);return e.indexOf(a)}:function(e,a){for(var d=e.length,b=!1;d--&&!b&&!(b=e[d]===a););return d},each:function(e,a){for(var e=[].concat(e),d=e.length-1;0<=d;d--)a.call(e[d],
d,e[d])},isType:function(a,f){return"Null"===f&&null===a||"Undefined"===f&&void 0===a||"Number"===f&&isFinite(a)||Object.prototype.toString.call(a).slice(8,-1)===f},getGUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var f=16*Math.random()|0;return("x"==a?f:f&3|8).toString(16)}).toUpperCase()},encodeHTML:function(a){a=h.isType(a,"String")?a:"";return a.replace(/\&/g,"&amp;").replace(/\>/g,"&gt;").replace(/\</g,"&lt;").replace(/\'/g,"&#039;").replace(/\"/g,"&quot;")},
decodeHTML:function(a){a=h.isType(a,"String")?a:"";return a.replace(/(&quot;)/g,'"').replace(/(&#039;)/ig,"'").replace(/(&lt;)/ig,"<").replace(/(&gt;)/ig,">").replace(/(&amp;)/ig,"&")},Enum:function(){for(var a={},f=0;f<arguments.length;f++)a[arguments[f]]=arguments[f];return a},documentWriteScript:function(e){var f=function(d){var b=/<script[^>]*?\bsrc\s*=\s*[\'"](.*?)['"][^>]*?>.*?(<\s*?\/script\s*?>)/ig,c=[],d=d&&d.replace(b,function(a,g){g&&c.push(g);return""});0<c.length&&a.base.BOM.Event.addEventListener(window,
"load",function(){a.base.BOM.loadJS(c)});e.call(document,d)};return function(a){document.write=a?f:e}}(document.write),setBaseURL:function(e){a.base.baseURL=e||a.base.baseURL},setCDNTimestamp:function(e){var f=a.base;f.CDNTimestamp=e||f.CDNTimestamp},trim:function(a){return a.replace(/(^\s+)|(\s+$)/g,"")},queryStringBuilder:function(a){function f(a){a=a&&a.toLowerCase();return h.ArrayIndexOf(c,a)}function d(a,b){if(a&&b){var d=f(a);0<=d&&d<g.length?g[d]=b:(j.push(a),g.push(b),c.push(a.toLowerCase()))}return b}
var b=arguments.callee;if(!(this instanceof b))return new b(a);var c=[],j=[],g=[];if(a&&(b=a.split("&")))for(var i=b.length-1;0<=i;i--){var l=b[i],k=l&&l.split("="),l=k&&k[0],k=k&&k[1];l&&d(l,k)}var o=function(c){try{c=c?decodeURIComponent(c):""}catch(a){}return encodeURIComponent(c).replace(/\*/g,"%2A").replace(/-/g,"%2D").replace(/_/g,"%5F").replace(/\./g,"%2E").replace(/!/g,"%21").replace(/~/g,"%7E").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29")};this.set=d;this.get=function(c){return c?
g[f(c)]:""};this.remove=function(a){var b=f(a);a&&0<b?(j.splice(b,1),g.splice(b,1),c.splice(b,1)):(j=[],g=[],c=[])};this.toString=function(c,a){for(var c=c||"=",a=a||"&",b=[],d=0;d<j.length;d++)g[d]&&b.push(o(j[d])+c+o(g[d]));return b.join(a)||""}}};h.merge(base,h)})(NEG);
(function(a){function h(c){var a=0<=(a=e.ArrayIndexOf(b,c))?a:b.push(c)-1;return a}var e=a.base||{},f={},d=[],b=[];f.addEventListener=function(c,a,b,e){e=e||{};e.Parameter=e.Parameter||[];var f=h(c),a=d[a]=d[a]||{},f=a[f]=a[f]||[];f.eventHandleAction=f.eventHandleAction||function(){};f.push({target:c,eventHandle:b,Parameter:e.Parameter});f.eventHandleAction=function(a){return function(j){var d={target:c};a.call(c,d,j);b.call(c,d,j)}}(f.eventHandleAction)};f.removeEventListener=function(c,a,b){c=h(c);
a=d[a][c];a.eventHandleAction=function(){};for(c=a.length-1;0<=c;c--)a[c]&&a[c].eventHandle==b||!b?a.splice(c,1):a.eventHandleAction=function(a,c){return function(){c.eventHandle.apply(c.target,c.Parameter);a()}}(a.eventHandleAction,a[c])};f.dispatchEvent=function(a,b,g){var e={target:a},f=h(a);if((b=d[b])&&b[f])for(var k=0;k<b[f].length;k++)b[f][k].eventHandle.call(a,e,g)};f.publicDispatchEvent=function(a,d){for(var g=0;g<b.length;g++){var e=b[g];e&&f.dispatchEvent(e,a,d)}};e.Event=e.Event||{};e.Event=
f})(NEG);
(function(a){function h(){for(var a=0,b=d.requireQueue.length;a<b;a++)if(!d.moduleLoaded[d.requireQueue[a]])return!1;return!0}function e(){a.base.Event.publicDispatchEvent(f.COMPLETE);a.base.BOM.Event.dispatchEvent(document,"readystatechange");e=function(){a.base.Event.publicDispatchEvent(f.COMPLETE)}}var f={COMPLETE:"require_complete_"+~~new Date,LOADED:"require_loaded_"+~~new Date,REQUIREING:"require_requireing_"+~~new Date},d={requiring:{},required:{},moduleLoaded:{},requireQueue:[]};a.base.Event.addEventListener(d,
f.REQUIREING,function(a,b){var g=b.moduleName.toLowerCase();d.required[g]=!0;d.requireQueue.push(g)});var b=function(c,b){function g(c){c.match(/(^.*)(\.\w*)$/);var b=a.base.CDNTimestamp||"";return a.base.baseURL+c.replace(/\./ig,"/")+".js"+(b&&"?"+b)}var f=c,c=c.toLowerCase();if(d.required[c]||d.requiring[c]||d.moduleLoaded[c])return a.base.NS(c,a.base);b=b||g(f);c=c.toLowerCase();d.requireQueue.push(c);(function(c){!d.required[c]&&!d.requiring[c]&&!d.moduleLoaded[c]&&(d.requiring[c]=!0,a.base.BOM.loadJS(b,
function(){if(!d.required[c])throw Error("module ["+c+"] is undefined! @"+b);h()&&e()}))})(c);return a.base.NS(c,a.base)};a.base.Event.addEventListener(b,f.LOADED,function(a,b){var g=b.moduleName.toLowerCase();d.required[g]=!0;d.moduleLoaded[g]=!0;h()&&e()});b.Event=f;b.isRequireComplete=h;a.base.Require=b})(NEG);
(function(a){var h={};a.base.Module=function(e,f){function d(){var b=j.toLowerCase(),d=c.toLowerCase(),g=a.base,i=g.NS,m=g.NS(c.toLowerCase(),g)[b],n=f(g.Require,g.run);m?"function"==typeof n?i(d,g)[b]=g.merge(n,m):g.merge(m,n):i(d,g)[b]=n;h[e]=!0;g.Event.publicDispatchEvent(g.Require.Event.LOADED,{moduleName:e})}var b=a.base;b.Event.publicDispatchEvent(b.Require.Event.REQUIREING,{moduleName:e});var b=e.match(/(^.*)\.(\w*)$/),c=b[1],j=b[2],b=f.toString().replace(/(?!['"])\/\*[\w\W]*?\*\//igm,""),
b=b.replace(/(['"])[\w\W]*?\1|((['"])[\w\W]*?)\/\/[\w\W]*?\2|\/\/[\w\W]*?(\r|\n|$)/g,function(a,c){return c?a:""}),g=b.replace(/^function\s*?\(\s*?([^,\)]+)[\w\W]*$/i,function(a,c){return c}).replace(b,""),g=g&&RegExp("\\b"+g+"\\s*\\(([^\\)]+)\\)","igm"),i=[];g&&b.replace(g,function(c,b){var g=b.replace(/['"]/g,"");h[g]||(i[g]=i.push(g)-1);a.base.Require(g)});i.length&&a.base.Event.addEventListener(e,a.base.Require.Event.LOADED,function(c,b){var g=b.moduleName;i.hasOwnProperty(g)&&(delete i[g],i.splice(i[g],
1));0>=i.length&&(a.base.Event.removeEventListener(e,a.base.Require.Event.LOADED),d())});i.length||d()}})(NEG);
(function(a){var h=[],e=function(){function d(){for(;function(){var a=h.shift();a&&a();return h.length}(););}var b=a.base.Event,c=a.base.Require.Event;this.run=function(c){h.push(c);a.base.Require.isRequireComplete()&&d()};this.require=function(c,b){a.base.Require(c,b);if(!b){var d=c.toLowerCase().match(/(^.*)\.(\w*)$/),e=d[2];a.base.NS(d[1],a.base);e.toLowerCase()}return a.base.NS(c.toLowerCase(),a.base)};b.addEventListener(this,c.COMPLETE,d)},f=function(a){var b=f;if(!(this instanceof b))return new b(a);
e.call(this);var c=this,b=a.toString().replace(/(?!['"])\/\*[\w\W]*?\*\//igm,""),b=b.replace(/(['"])[\w\W]*?\1|((['"])[\w\W]*?)\/\/[\w\W]*?\2|\/\/[\w\W]*?(\r|\n|$)/g,function(a,c){return c?a:""}),j=b.replace(/^function\s*?\(\s*?([^,\)]+)[\w\W]*$/i,function(a,c){return c}).replace(b,"");(j=j&&RegExp("\\b"+j+"\\s*\\(([^\\)]+)\\)","igm"))&&b.replace(j,function(a,b){c.require(b.replace(/['"]/g,""))});c.run(function(){a(c.require,c.run)})};a.base.run=f})(NEG);
(function(a){function h(a,b,g){return function(b){g.call(a,b)}}function e(a,d,g){function e(b){f.eventAction=function(b,g){return function(d){b&&b.call(a,d);g.call(a,d)}}(f.eventAction,b)}var f=b[a.GUID][d];if(g)e(g);else for(d=0;d<f.length;d++)e(f[d]);return f.eventAction}function f(a,d,g,e){e=e||{};g=b[a.GUID][d][g];if(d&&g)a.removeEventListener?a.removeEventListener(d,g,!1):a.detachEvent&&a.detachEvent("on"+d,g);else if(d&&!g)for(var h=0;h<b[a.GUID][d].length;h++)f(a,d,b[a.GUID][d][h],e);else for(h in d=
b[a.GUID],d)f(a,h)}var d=a.base||{},b={};d.NS("NEG.base.BOM").Event={addEventListener:function(a,f,g){a.GUID=a.GUID||d.getGUID();var g=h(a,f,g),i=d.NS(a.GUID,b)[f]=d.NS(a.GUID,b)[f]||[];i.push(g);i[g]=g;i.eventAction=e(a,f,g);a.addEventListener?a.addEventListener(f,g,!1):a.attachEvent&&a.attachEvent("on"+f,g)},removeEventListener:f,dispatchEvent:function(a,b,d){d=d||{bubbles:!1,cancelable:!1};d.ieHack=a.all&&a.all.toString();if(document.createEvent){var e=document.createEvent("Event");e.initEvent(b,
d.bubbles,d.cancelable);a.dispatchEvent(e)}else if(document.createEventObject)b="on"+b,e=document.createEventObject(),e.cancelBubble=d.cancelable,a.fireEvent(b,e)},isEventSupported:function(a,b){if(!d.BOM.Utility.isHTMLElement(a))return!1;var g=a.tagName,b="on"+b,a=a===window?window:document.createElement(g),g=b in a;!g&&"setAttribute"in window&&(a.setAttribute(b,"return;"),g="function"===typeof a[b]);return g}}})(NEG);
(function(a){function h(){try{document.documentElement.doScroll("left")}catch(a){setTimeout(h,1);return}d()}var e=!1,f=[],d=function(){a.base.BOM.Event.removeEventListener(document,"readystatechange",b);a.base.BOM.Event.removeEventListener(document,"DOMContentLoaded",d);a.base.BOM.Event.removeEventListener(window,"load",d);for(var c;c=f.shift();)e||c();e=!0},b=function(){(/loaded|complete/.test(document.readyState)||!0==e)&&d()};a.base.BOM.Event.addEventListener(document,"readystatechange",b);a.base.BOM.Event.addEventListener(document,
"DOMContentLoaded",d);a.base.BOM.Event.addEventListener(window,"load",d);document.documentElement.doScroll&&h();base.NS("NEG.base.BOM").DOMReady=function(a){!0==e?a():f.push(a)}})(NEG);
(function(a,h){function e(a,c){var e=1;this.loadJS=function(){if(/\bArray\b/.test(Object.prototype.toString.call(a))){e=a.length;for(var g=e-1;0<=g;g--)d(a[g],function(){--e||c()})}else d(a,c)}}function f(){function a(){if(!c.currentJs)c.currentJs=c.shift(),c.currentJs&&c.currentJs.loadJS()}var c=[];c.currentJs=null;this.loadJS=function(d,g){c.push(new e(d,function(){c.currentJs=null;g&&g();a()}));a();return this}}function d(a,c){var d=document.getElementsByTagName("head")[0],e=document.createElement("script"),
f=!1,l,k=function(){f=!0;h.base.BOM.Event.removeEventListener(e,"load",k);h.base.BOM.Event.removeEventListener(e,"readystatechange",o);k=function(){};c&&c()},o=function(){/loaded|complete/.test(e.readyState)&&!1==f&&k()};e.async=!0;e.setAttribute("type","text/javascript");e.src=a;h.base.BOM.Event.addEventListener(e,"load",k);h.base.BOM.Event.addEventListener(e,"readystatechange",o);for(var p=document.getElementsByTagName("script"),m=0,n=p.length;!l&&m<n;m++)l=a==p[m].getAttribute("src");l||d.appendChild(e)}
NEG.base.BOM[a]=function(a,c){var d=new f;d.loadJS(a,c);return d}})("loadJS",NEG);(function(a){var b;b=a.base.BOM=a.base.BOM||{},a=b;a.Utility=a.Utility||{};a.Utility.isHTMLElement=function(a){var e;if(window.HTMLElement)e=a instanceof HTMLElement;else{var f=a.nodeName;try{e=!delete a.nodeName,a.nodeName=f}catch(d){e=!0}}e||(e=a==document||a==window);return e}})(NEG);
(function(a){var h={run:a.base.run,on:function(){var e={},f=a.base,d=f.Event.publicDispatchEvent,b=f.Event.addEventListener;return function(a,h){var g=[].slice.call(arguments,0);h&&f.isType(h,"Function")?(g.unshift(e),b.apply(e,g)):d.apply(e,g)}}(a),loadJS:a.base.BOM.loadJS,Module:a.base.Module,merge:a.base.merge,NS:a.base.NS,ArrayIndexOf:a.base.ArrayIndexOf,isType:a.base.isType,encodeHTML:a.base.encodeHTML,decodeHTML:a.base.decodeHTML,Enum:a.base.Enum,documentWriteScript:a.base.documentWriteScript,
domReady:a.base.BOM.DOMReady,moduleURL:a.base.setBaseURL,setCDNTimestamp:a.base.setCDNTimestamp,trim:a.base.trim,queryStringBuilder:a.base.queryStringBuilder};a.base.merge(a.base.avatarCore,{on:function(e,f,d){var b=this.target,c=a.base,h=c.BOM.Utility.isHTMLElement(b)&&c.BOM.Event.isEventSupported(b,e)?c.BOM.Event.addEventListener:c.Event.addEventListener,g=c.BOM.Utility.isHTMLElement(b)&&c.BOM.Event.isEventSupported(b,e)?c.BOM.Event.dispatchEvent:c.Event.dispatchEvent;1==arguments.length?c.each(b,
function(a,b){g(b,e)}):c.each(b,function(a,b){h(b,e,f,d)})},off:function(e,f,d){if(!(0>=arguments.length)){var b=this.target,c=a.base,h=c.BOM.Utility.isHTMLElement(b)&&c.BOM.Event.isEventSupported(b,e)?c.BOM.Event.removeEventListener:c.Event.removeEventListener;c.each(b,function(a,b){h(b,e,f,d)})}}});a.base.merge(a,h);a.base.init()})(NEG);
